### PR TITLE
Release / V1

### PR DESCRIPTION
**Pull request by NicolJamie**
Well, here we are.. V1 of the rrd-api for your first pass @thomaspalmer at the PR!

### CODE REVIEW

**Comment by thomaspalmer** [comment]
@NicolJamie Looks like the config files are missing? base.php and payments.php

**Comment by NicolJamie** [comment]
> @NicolJamie Looks like the config files are missing? base.php and payments.php

I'll have a look when I'm home -- didn't get that far.

**Comment by thomaspalmer** [comment]
Also missing migrations?

**Comment by thomaspalmer** [comment]
> > @NicolJamie Looks like the config files are missing? base.php and payments.php
> 
> I'll have a look when I'm home -- didn't get that far.

Soz! Thought you wanted a review, I'll remove myself for now:)

**Comment by NicolJamie** [comment]
> > > @NicolJamie Looks like the config files are missing? base.php and payments.php
> 
> > 
> 
> > I'll have a look when I'm home -- didn't get that far.
> 
> 
> 
> Soz! Thought you wanted a review, I'll remove myself for now:)

Ah my bad -- just wanted a place to see the file changes. Habit

**Comment by thomaspalmer** [comment]
Need to look at:
- [ ] /invoices endpoint return 403
- [ ] /password/reset 500 error (no controller found)

**Comment by NicolJamie** [comment]
> Need to look at:
> 
> * [x]  /invoices endpoint return 403
> * [x]  /password/reset 500 error (no controller found)

I fixed the 401 issue with `invoices`, if you have a `403` are you requesting this before you've verified your email?

**Comment by thomaspalmer** [comment]
@NicolJamie Sorry, meant 401 on invoices but I'm still getting it. The Password reset is fixed.

**Comment by NicolJamie** [comment]
> @NicolJamie Sorry, meant 401 on invoices but I'm still getting it. The Password reset is fixed.

Composer update and try again :)

**Review by thomaspalmer — APPROVED** [review]

**Pull request merged**
